const overlay=document.querySelector(".overlay");const isMobile=screen.width<768;var currentPlan=2;function getByClass(className){return document.getElementsByClassName(className);}
function getById(id){return document.getElementById(id);}
function getByName(name){return document.getElementsByName(name);}
function changePlans(type){if(type==1){currentPlan=1;getById("toggle-btn").style.display="none";getById("plans-chatbot").style.display="none";getById("plans-mass-despatch").style.display="flex";if(isMobile){getByClass("selector-plans")[0].style.display="flex";getByClass("selector-plans")[1].style.display="none";getById("plans-mass-despatch").style.display='none';getById("plans-mass-despatch2").style.display='flex';}
getById("adicionais").style.display="none";getById("anual").style.display="none";getById("card-1").classList.add("active-card");getById("card-2").classList.remove("active-card");getById("plans-mass-despatch").style.opacity="0";getByClass("arrows")[1].classList.add("d-none");getByClass("arrows")[0].classList.remove("d-none");setTimeout(()=>{getById("plans-mass-despatch").style.opacity="1";},300)
getById("toggle-btn").style.opacity="0";setTimeout(()=>{getById("toggle-btn").style.opacity="1";},400)
const offSet=getByClass("plano-card-mensal")[0].offsetTop?getByClass("plano-card-mensal")[0].offsetTop-35:getByClass("plano-card-mensal")[1].offsetTop-35;window.scrollTo(0,offSet);}else{getById("toggle-btn").style.display="flex";getById("plans-chatbot").style.display="flex";getById("plans-mass-despatch").style.display="none";if(isMobile){getByClass("selector-plans")[1].style.display="flex";getByClass("selector-plans")[0].style.display="none";getById("plans-mass-despatch").style.display='none';getById("plans-mass-despatch2").style.display='none';}
getById("adicionais").style.display="block";getById("card-2").classList.add("active-card");getById("card-1").classList.remove("active-card");getById("toggle-btn").style.opacity="0";getByClass("arrows")[1].classList.remove("d-none");getByClass("arrows")[0].classList.add("d-none");setTimeout(()=>{getById("toggle-btn").style.opacity="1";},400)
getById("plans-chatbot").style.opacity="0";setTimeout(()=>{getById("plans-chatbot").style.opacity="1";},400)
window.scrollTo(0,getByClass("plano-card-basic")[0].offsetTop-135);};getById("bluetooth").checked=false;};function changePayment(){if(getById("plans-chatbot").style.display=="none"){getById("anual").style.display="none";getById("plans-chatbot").style.display="flex";}else{getById("anual").style.display="flex";getById("plans-chatbot").style.display="none";};};function scrollWin(){window.scrollTo(0,getByClass("plano-ideal")[0].offsetTop);};function carroselChange(event){const current=Array.from(getByName("position")).find(item=>item.checked).attributes[2].value;switch(event){case "prev":if(current==='1')getByName("position")[2].click();else document.querySelector(`[data-carrossel-item="${(parseInt(current)-1).toString()}"]`).click();break;case "next":if(current==='3')getByName("position")[0].click();else document.querySelector(`[data-carrossel-item="${(parseInt(current)+1).toString()}"]`).click();break;};}
Array.from(document.querySelectorAll('[data-toggle="collapse"]')).forEach(val=>{val.addEventListener("click",(e)=>{const currentId=e.target.attributes[3].value.replace("#","");Array.from(getByClass("mobile-hidden-collapse")).forEach(val=>{if(val.id!=currentId&&isMobile)val.classList.remove("show");});});});if(!isMobile){getById("mobile-table").classList.remove("table-mobile");getById("mobile-table").classList.remove("table-responsive");}
if(!isMobile){getById("mobile-table-chatbot").classList.remove("table-mobile");getById("mobile-table-chatbot").classList.remove("table-responsive");}
const plansPosition={first:190,second:519,thirth:1008,}
function scrollElement(event){if(event==2){switch(currentPlan){case 1:scrollPlans(336,0);removeArrow(1);break;case 2:scrollPlans(672,0);addArrow(2);break;}}else{switch(currentPlan){case 2:scrollPlans(0,0);addArrow(1);break;case 3:scrollPlans(336,0);removeArrow(2);break;}}}
function scrollPlans(x,y){Array.from(getByClass("table-mobile")).forEach(val=>{val.scrollTo(x,y);})}
function handleArrows(e){if(e.target.scrollLeft<plansPosition.first){currentPlan=1;addArrow(1);getByClass("plano-card-mensal")[1].classList.add('card-styled')
getByClass("plano-card-mensal")[0].classList.add('card-styled')
getByClass("plano-card-trimestral")[1].classList.remove('card-styled')
getByClass("plano-card-trimestral")[0].classList.remove('card-styled')
getByClass("plano-card-anual")[1].classList.remove('card-styled')
getByClass("plano-card-anual")[0].classList.remove('card-styled')
getByClass("selector1")[0].classList.add('card-select')
getByClass("selector1")[0].classList.add('card-select')
getByClass("selector2")[0].classList.remove('card-select')
getByClass("selector2")[0].classList.remove('card-select')
getByClass("selector3")[0].classList.remove('card-select')
getByClass("selector3")[0].classList.remove('card-select')
getByClass("selector1")[1].classList.add('card-select')
getByClass("selector1")[1].classList.add('card-select')
getByClass("selector2")[1].classList.remove('card-select')
getByClass("selector2")[1].classList.remove('card-select')
getByClass("selector3")[1].classList.remove('card-select')
getByClass("selector3")[1].classList.remove('card-select')
getByClass("plano-card-basic")[1].classList.add('card-styled')
getByClass("plano-card-basic")[0].classList.add('card-styled')
getByClass("plano-card-premium")[1].classList.remove('card-styled')
getByClass("plano-card-premium")[0].classList.remove('card-styled')
getByClass("plano-card-business")[1].classList.remove('card-styled')
getByClass("plano-card-business")[0].classList.remove('card-styled')}else if(e.target.scrollLeft>=plansPosition.first&&e.target.scrollLeft<plansPosition.second){currentPlan=2;removeArrow(1);removeArrow(2);getByClass("plano-card-mensal")[1].classList.remove('card-styled')
getByClass("plano-card-mensal")[0].classList.remove('card-styled')
getByClass("plano-card-trimestral")[1].classList.add('card-styled')
getByClass("plano-card-trimestral")[0].classList.add('card-styled')
getByClass("plano-card-anual")[1].classList.remove('card-styled')
getByClass("plano-card-anual")[0].classList.remove('card-styled')
getByClass("selector1")[0].classList.remove('card-select')
getByClass("selector1")[0].classList.remove('card-select')
getByClass("selector2")[0].classList.add('card-select')
getByClass("selector2")[0].classList.add('card-select')
getByClass("selector3")[0].classList.remove('card-select')
getByClass("selector3")[0].classList.remove('card-select')
getByClass("selector1")[1].classList.remove('card-select')
getByClass("selector1")[1].classList.remove('card-select')
getByClass("selector2")[1].classList.add('card-select')
getByClass("selector2")[1].classList.add('card-select')
getByClass("selector3")[1].classList.remove('card-select')
getByClass("selector3")[1].classList.remove('card-select')
getByClass("plano-card-basic")[1].classList.remove('card-styled')
getByClass("plano-card-basic")[0].classList.remove('card-styled')
getByClass("plano-card-premium")[1].classList.add('card-styled')
getByClass("plano-card-premium")[0].classList.add('card-styled')
getByClass("plano-card-business")[1].classList.remove('card-styled')
getByClass("plano-card-business")[0].classList.remove('card-styled')}else{currentPlan=3;addArrow(2);getByClass("plano-card-mensal")[1].classList.remove('card-styled')
getByClass("plano-card-mensal")[0].classList.remove('card-styled')
getByClass("plano-card-trimestral")[1].classList.remove('card-styled')
getByClass("plano-card-trimestral")[0].classList.remove('card-styled')
getByClass("plano-card-anual")[1].classList.add('card-styled')
getByClass("plano-card-anual")[0].classList.add('card-styled')
getByClass("selector1")[0].classList.remove('card-select')
getByClass("selector1")[0].classList.remove('card-select')
getByClass("selector2")[0].classList.remove('card-select')
getByClass("selector2")[0].classList.remove('card-select')
getByClass("selector3")[0].classList.add('card-select')
getByClass("selector3")[0].classList.add('card-select')
getByClass("selector1")[1].classList.remove('card-select')
getByClass("selector1")[1].classList.remove('card-select')
getByClass("selector2")[1].classList.remove('card-select')
getByClass("selector2")[1].classList.remove('card-select')
getByClass("selector3")[1].classList.add('card-select')
getByClass("selector3")[1].classList.add('card-select')
getByClass("plano-card-basic")[1].classList.remove('card-styled')
getByClass("plano-card-basic")[0].classList.remove('card-styled')
getByClass("plano-card-premium")[1].classList.remove('card-styled')
getByClass("plano-card-premium")[0].classList.remove('card-styled')
getByClass("plano-card-business")[1].classList.add('card-styled')
getByClass("plano-card-business")[0].classList.add('card-styled')}}
getById("mobile-table").addEventListener('scroll',handleArrows)
getById("mobile-table-chatbot").addEventListener('scroll',handleArrows)
function removeArrow(event){const currentType=getById("plans-chatbot").style.display=="none"&&getById("anual").style.display=="none"?"sender":"chat";if(event===1){Array.from(getByClass("arrow-prev-plans")).forEach(val=>{if(currentType==="sender"&&val.classList.contains("arrow-sender")){val.classList.remove("d-none")}else if(currentType==="chat"&&val.classList.contains("arrow-chat")){val.classList.remove("d-none");}})}else{Array.from(getByClass("arrow-next-plans")).forEach(val=>{if(currentType==="sender"&&val.classList.contains("arrow-sender")){val.classList.remove("d-none")}else if(currentType==="chat"&&val.classList.contains("arrow-chat")){val.classList.remove("d-none");}})}}
function addArrow(event){const currentType=getById("plans-chatbot").style.display=="none"&&getById("anual").style.display=="none"?"sender":"chat";console.log(currentType);if(event===1){Array.from(getByClass("arrow-prev-plans")).forEach(val=>{if(currentType==="sender"&&val.classList.contains("arrow-sender")){val.classList.add("d-none")}else if(currentType==="chat"&&val.classList.contains("arrow-chat")){val.classList.add("d-none");}})}else{Array.from(getByClass("arrow-next-plans")).forEach(val=>{if(currentType==="sender"&&val.classList.contains("arrow-sender")){val.classList.add("d-none")}else if(currentType==="chat"&&val.classList.contains("arrow-chat")){val.classList.add("d-none");}})}}